name: Map Feature
description: 'Suggest a feature or improvement to maps.'
title: '[MAP NAME] Replace this with short description'
labels:
  - feature
  - maps
body:
  - type: input
    id: map-name
    attributes:
      label: Map name
      description: What map do you want to suggest a change for?
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: 'Example: "I''m always frustrated when [...]"'
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to change with the map.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.