name: Map Bug
description: 'Found an issue with a map?'
title: '[MAP NAME] Replace this with short description'
labels:
  - bug
  - maps
body:
  - type: input
    id: map-name
    attributes:
      label: Map name
      description: What map is affected by the bug?
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your report.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
