name: Server Issue
description: 'Report any issues with the servers on Overcast Community.'
labels:
  - bug
  - server
body:
  - type: markdown
    attributes:
      value: >-
        ## If the bug is related to PGM, report at their [issues
        tracker](https://github.com/PGMDev/PGM/issues).
  - type: input
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: bug-reproduction-steps
    attributes:
      label: Steps to reproduce the behavior
      description: Please make a numbered list showing how the bug works in detail.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: client-information
    attributes:
      label: Client information
      description: Please complete the following information.
      value: |-
        **Minecraft version:** 
        **Any mods installed?:** 
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
